x-general_sc4snmp_data: &general_sc4snmp_data
  CONFIG_PATH: /app/config/config.yaml
  REDIS_URL: redis://redis:6379/1
  CELERY_BROKER_URL: redis://redis:6379/0
  MONGO_URI: mongodb://mongo:27017/
  MIB_SOURCES: http://snmp-mibserver:8000/asn1/@mib@
  MIB_INDEX: http://snmp-mibserver:8000/index.csv
  MIB_STANDARD: http://snmp-mibserver:8000/standard.txt

x-splunk_general_setup: &splunk_general_setup
  SPLUNK_HEC_HOST: ${SPLUNK_HEC_HOST}
  SPLUNK_HEC_SCHEME: ${SPLUNK_HEC_PROTOCOL:-https}
  SPLUNK_HEC_PORT: ${SPLUNK_HEC_PORT}
  SPLUNK_HEC_TOKEN: ${SPLUNK_HEC_TOKEN}
  SPLUNK_HEC_INSECURESSL: ${SPLUNK_HEC_INSECURESSL:-false}
  SPLUNK_HEC_PATH: ${SPLUNK_HEC_PATH:-/services/collector}

x-splunk_extended_setup: &splunk_extended_setup
  SPLUNK_SOURCETYPE_TRAPS: ${SPLUNK_SOURCETYPE_TRAPS:-sc4snmp:traps}
  SPLUNK_SOURCETYPE_POLLING_EVENTS: ${SPLUNK_SOURCETYPE_POLLING_EVENTS:-sc4snmp:event}
  SPLUNK_SOURCETYPE_POLLING_METRICS: ${SPLUNK_SOURCETYPE_POLLING_METRICS:-sc4snmp:metric}
  SPLUNK_HEC_INDEX_EVENTS: ${SPLUNK_HEC_INDEX_EVENTS:-netops}
  SPLUNK_HEC_INDEX_METRICS: ${SPLUNK_HEC_INDEX_METRICS:-netmetrics}
  SPLUNK_AGGREGATE_TRAPS_EVENTS: ${SPLUNK_AGGREGATE_TRAPS_EVENTS:-false}
  SPLUNK_METRIC_NAME_HYPHEN_TO_UNDERSCORE: ${SPLUNK_METRIC_NAME_HYPHEN_TO_UNDERSCORE:-false}

x-workers_general_setup: &workers_general_setup
  SC4SNMP_VERSION: ${SC4SNMP_VERSION:-latest}
  IGNORE_EMPTY_VARBINDS: ${IGNORE_EMPTY_VARBINDS:-false}
  WALK_RETRY_MAX_INTERVAL: ${WALK_RETRY_MAX_INTERVAL:-180}
  WALK_MAX_RETRIES: ${WALK_MAX_RETRIES:-5}
  METRICS_INDEXING_ENABLED: ${METRICS_INDEXING_ENABLED:-false}
  POLL_BASE_PROFILES: ${POLL_BASE_PROFILES:-true}
  IGNORE_NOT_INCREASING_OIDS: ${IGNORE_NOT_INCREASING_OIDS:-}
  LOG_LEVEL: ${WORKER_LOG_LEVEL:-INFO}
  DISABLE_MONGO_DEBUG_LOGGING: ${WORKER_DISABLE_MONGO_DEBUG_LOGGING:-true}
  UDP_CONNECTION_TIMEOUT: ${UDP_CONNECTION_TIMEOUT:-3}
  MAX_OID_TO_PROCESS: ${MAX_OID_TO_PROCESS:-70}
  MAX_REPETITIONS: ${MAX_REPETITIONS:-10}
  MAX_SNMP_BULK_WALK_CONCURRENCY: ${MAX_SNMP_BULK_WALK_CONCURRENCY:-5}
  PROFILES_RELOAD_DELAY: ${PROFILES_RELOAD_DELAY:-60}

x-ipv6: &ipv6
  IPv6_ENABLED: ${IPv6_ENABLED:-false}

x-pysnmp_debug: &pysnmp_debug
  PYSNMP_DEBUG: ${PYSNMP_DEBUG}

x-dns_and_networks: &dns_and_networks
  networks:
  - sc4snmp_network
  dns:
  - ${COREDNS_ADDRESS}
  - ${COREDNS_ADDRESS_IPv6}

x-dependency_and_restart_policy: &dependency_and_restart_policy
  depends_on:
  - redis
  - mongo
  - coredns
  restart: on-failure

x-dependend_on_core_dns: &dependend_on_core_dns
  depends_on:
  - coredns

secrets: {}

networks:
  sc4snmp_network:
    name: sc4snmp_network
    enable_ipv6: ${IPv6_ENABLED:-false}
    ipam:
      config:
      - subnet: ${IPAM_SUBNET:-172.28.0.0/16}
        gateway: ${IPAM_GATEWAY:-172.28.0.1}
      - subnet: ${IPAM_SUBNET_IPv6:-fd02::/64}
        gateway: ${IPAM_GATEWAY_IPv6:-fd02::1}

services:
  coredns:
    image: ${COREDNS_IMAGE}:${COREDNS_TAG:-latest}
    command: [-conf, /Corefile]
    container_name: coredns
    restart: on-failure
    expose:
    - '53'
    - 53/udp
    volumes:
    - ${COREFILE_ABS_PATH}:/Corefile
    networks:
      sc4snmp_network:
        ipv4_address: ${COREDNS_ADDRESS}
        ipv6_address: ${COREDNS_ADDRESS_IPv6}
  snmp-mibserver:
    <<: [*dns_and_networks, *dependend_on_core_dns]
    image: ${MIBSERVER_IMAGE}:${MIBSERVER_TAG:-latest}
    container_name: snmp-mibserver
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: ${NGINX_ENTRYPOINT_QUIET_LOGS:-1}
    volumes:
    - snmp-mibserver-tmp:/tmp/
  redis:
    <<: [*dns_and_networks, *dependend_on_core_dns]
    image: ${REDIS_IMAGE}:${REDIS_TAG:-latest}
    container_name: redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes
  mongo:
    <<: [*dns_and_networks, *dependend_on_core_dns]
    image: ${MONGO_IMAGE}:${MONGO_TAG:-latest}
    container_name: mongo
  inventory:
    <<: [*dns_and_networks, *dependency_and_restart_policy]
    image: ${SC4SNMP_IMAGE}:${SC4SNMP_TAG:-latest}
    container_name: sc4snmp-inventory
    command: [inventory]
    environment:
      <<: *general_sc4snmp_data
      LOG_LEVEL: ${INVENTORY_LOG_LEVEL:-INFO}
      CHAIN_OF_TASKS_EXPIRY_TIME: ${CHAIN_OF_TASKS_EXPIRY_TIME:-500}
      CONFIG_FROM_MONGO: ${CONFIG_FROM_MONGO:-false}
      ENABLE_FULL_WALK: ${ENABLE_FULL_WALK:-false}
    volumes:
    - ${SCHEDULER_CONFIG_FILE_ABSOLUTE_PATH}:/app/config/config.yaml:ro
    - ${INVENTORY_FILE_ABSOLUTE_PATH}:/app/inventory/inventory.csv:ro
    - inventory-pysnmp-cache-volume:/.pysnmp/:rw
    - inventory-tmp:/tmp/:rw
  scheduler:
    <<: [*dns_and_networks, *dependency_and_restart_policy]
    image: ${SC4SNMP_IMAGE}:${SC4SNMP_TAG:-latest}
    container_name: sc4snmp-scheduler
    command: [celery, beat]
    environment:
      <<: *general_sc4snmp_data
      LOG_LEVEL: ${SCHEDULER_LOG_LEVEL:-INFO}
    volumes:
    - ${SCHEDULER_CONFIG_FILE_ABSOLUTE_PATH}:/app/config/config.yaml:ro
    - scheduler-pysnmp-cache-volume:/.pysnmp/:rw
    - scheduler-tmp:/tmp/:rw
  traps:
    <<: [*dns_and_networks, *dependency_and_restart_policy]
    command:
    - trap
    container_name: sc4snmp-traps
    environment:
      <<: [*general_sc4snmp_data, *splunk_general_setup, *pysnmp_debug, *ipv6]
      LOG_LEVEL: ${TRAP_LOG_LEVEL:-INFO}
      SNMP_V3_SECURITY_ENGINE_ID: ${SNMP_V3_SECURITY_ENGINE_ID:-80003a8c04}
      DISABLE_MONGO_DEBUG_LOGGING: ${TRAP_DISABLE_MONGO_DEBUG_LOGGING:-true}
    image: ${SC4SNMP_IMAGE}:${SC4SNMP_TAG:-latest}
    ports:
    - mode: host
      protocol: udp
      published: ${TRAPS_PORT}
      target: 2162
    volumes:
    - ${TRAPS_CONFIG_FILE_ABSOLUTE_PATH}:/app/config/config.yaml:ro
    - traps-pysnmp-cache-volume:/.pysnmp/:rw
    - traps-tmp:/tmp/:rw
  worker-poller:
    <<: [*dns_and_networks, *dependency_and_restart_policy]
    image: ${SC4SNMP_IMAGE}:${SC4SNMP_TAG:-latest}
    command:
    - celery
    - worker-poller
    deploy:
      mode: replicated
      replicas: ${WORKER_POLLER_REPLICAS:-2}
      resources:
        limits:
          cpus: ${WORKER_POLLER_CPU_LIMIT:-0.50}
          memory: ${WORKER_POLLER_MEMORY_LIMIT:-500M}
        reservations:
          cpus: ${WORKER_POLLER_CPU_RESERVATIONS:-0.25}
          memory: ${WORKER_POLLER_MEMORY_RESERVATIONS:-250M}
    environment:
      <<: [*general_sc4snmp_data, *splunk_general_setup, *splunk_extended_setup, *workers_general_setup,
        *pysnmp_debug, *ipv6]
      WORKER_CONCURRENCY: ${WORKER_POLLER_CONCURRENCY:-2}
      PREFETCH_COUNT: ${PREFETCH_POLLER_COUNT:-1}
    volumes:
    - ${SCHEDULER_CONFIG_FILE_ABSOLUTE_PATH}:/app/config/config.yaml:ro
    - worker-poller-pysnmp-cache-volume:/.pysnmp/:rw
    - worker-poller-tmp:/tmp/:rw
  worker-sender:
    <<: [*dns_and_networks, *dependency_and_restart_policy]
    image: ${SC4SNMP_IMAGE}:${SC4SNMP_TAG:-latest}
    command: [celery, worker-sender]
    environment:
      <<: [*general_sc4snmp_data, *splunk_general_setup, *splunk_extended_setup, *workers_general_setup,
        *pysnmp_debug]
      # OTEL_METRICS_URL:  #If sim enabled
      # Workers configuration
      WORKER_CONCURRENCY: ${WORKER_SENDER_CONCURRENCY:-2}
      PREFETCH_COUNT: ${PREFETCH_SENDER_COUNT:-1}
    volumes:
    - ${SCHEDULER_CONFIG_FILE_ABSOLUTE_PATH}:/app/config/config.yaml:ro
    - worker-sender-pysnmp-cache-volume:/.pysnmp/:rw
    - worker-sender-tmp:/tmp/:rw
    deploy:
      mode: replicated
      replicas: ${WORKER_SENDER_REPLICAS:-1}
      resources:
        limits:
          cpus: ${WORKER_SENDER_CPU_LIMIT:-0.50}
          memory: ${WORKER_SENDER_MEMORY_LIMIT:-500M}
        reservations:
          cpus: ${WORKER_SENDER_CPU_RESERVATIONS:-0.25}
          memory: ${WORKER_SENDER_MEMORY_RESERVATIONS:-250M}
  worker-trap:
    <<: [*dns_and_networks, *dependency_and_restart_policy]
    image: ${SC4SNMP_IMAGE}:${SC4SNMP_TAG:-latest}
    command: [celery, worker-trap]
    environment:
      <<: [*general_sc4snmp_data, *splunk_general_setup, *splunk_extended_setup, *workers_general_setup,
        *pysnmp_debug, *ipv6]
      # OTEL_METRICS_URL:  #If sim enabled
      # Workers configuration
      WORKER_CONCURRENCY: ${WORKER_TRAP_CONCURRENCY:-2}
      PREFETCH_COUNT: ${PREFETCH_TRAP_COUNT:-1}
      RESOLVE_TRAP_ADDRESS: ${RESOLVE_TRAP_ADDRESS:-false}
      MAX_DNS_CACHE_SIZE_TRAPS: ${MAX_DNS_CACHE_SIZE_TRAPS:-500}
      TTL_DNS_CACHE_TRAPS: ${TTL_DNS_CACHE_TRAPS:-1800}
    volumes:
    - ${SCHEDULER_CONFIG_FILE_ABSOLUTE_PATH}:/app/config/config.yaml:ro
    - worker-trap-pysnmp-cache-volume:/.pysnmp/:rw
    - worker-trap-tmp:/tmp/:rw
    deploy:
      mode: replicated
      replicas: ${WORKER_TRAP_REPLICAS:-2}
      resources:
        limits:
          cpus: ${WORKER_TRAP_CPU_LIMIT:-0.50}
          memory: ${WORKER_TRAP_MEMORY_LIMIT:-500M}
        reservations:
          cpus: ${WORKER_TRAP_CPU_RESERVATIONS:-0.25}
          memory: ${WORKER_TRAP_MEMORY_RESERVATIONS:-250M}
  flower:
    <<: [*dns_and_networks, *dependency_and_restart_policy]
    image: ${SC4SNMP_IMAGE}:${SC4SNMP_TAG:-latest}
    command: [celery, flower]
    environment:
      <<: [
        *general_sc4snmp_data,
        *splunk_general_setup,
        *splunk_extended_setup,
        *workers_general_setup,
        *pysnmp_debug
      ]
    profiles: [debug]
    ports:
    - mode: host
      protocol: tcp
      published: ${FLOWER_PORT}
      target: 5555
    volumes:
    - ${SCHEDULER_CONFIG_FILE_ABSOLUTE_PATH}:/app/config/config.yaml:ro
    - worker-flower-pysnmp-cache-volume:/.pysnmp/:rw
    - worker-flower-tmp:/tmp/:rw
volumes:
  snmp-mibserver-tmp:
  inventory-tmp:
  inventory-pysnmp-cache-volume:
  scheduler-tmp:
  scheduler-pysnmp-cache-volume:
  traps-pysnmp-cache-volume:
  traps-tmp:
  worker-poller-pysnmp-cache-volume:
  worker-poller-tmp:
  worker-sender-tmp:
  worker-sender-pysnmp-cache-volume:
  worker-trap-tmp:
  worker-trap-pysnmp-cache-volume:
  worker-flower-tmp:
  worker-flower-pysnmp-cache-volume:
