apiVersion: v1
kind: Service
metadata:
  name: sc4-snmp-traps
spec:
  type: LoadBalancer
  loadBalancerIP: replace-me
  ports:
    - port: 162
      targetPort: 2162
      protocol: UDP
  selector:
    app: sc4-snmp-traps
---
