{{- if .Values.splunkSIM.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "splunk-connect-for-snmp.name" . }}-otel
  namespace: {{ .Release.Namespace | quote }}
data:
  otel-collector-config.yaml: |
    receivers:
      splunk_hec/metrics:
        endpoint: 0.0.0.0:8882
    exporters:
      signalfx:
        access_token: $signalfxToken
        realm: $signalfxRealm
    service:
      pipelines:
        metrics:
          receivers: [splunk_hec/metrics]
          exporters: [signalfx]
{{- end }}
