{{- if .Values.splunk.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "splunk-connect-for-snmp.name" . }}-splunk
type: Opaque
data:
  hec_token: {{ .Values.splunk.token | b64enc | quote }}
{{- end }}