{{- if .Values.sim.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "splunk-connect-for-snmp.sim.fullname" . }}
  labels:
    {{- include "splunk-connect-for-snmp.sim.labels" . | nindent 4 }}
spec:
  {{- if not .Values.sim.autoscaling.enabled }}
  replicas: {{ .Values.sim.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "splunk-connect-for-snmp.sim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.sim.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "splunk-connect-for-snmp.sim.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "splunk-connect-for-snmp.sim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.sim.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-sim
          securityContext:
            {{- toYaml .Values.sim.securityContext | nindent 12 }}
          image: {{ .Values.sim.image | default "quay.io/signalfx/splunk-sim-collector" }}:{{ .Values.sim.tag | default "0.41.0" }}
          imagePullPolicy: {{ .Values.sim.pullPolicy | default "IfNotPresent" }}
          args: ["--config=/config/sim-collector-config.yaml"]
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: signalfxToken
              valueFrom:
                secretKeyRef:
                  name: {{ include "splunk-connect-for-snmp.name" . }}-sim
                  key: signalfxToken
            - name: signalfxRealm
              valueFrom:
                secretKeyRef:
                  name: {{ include "splunk-connect-for-snmp.name" . }}-sim
                  key: signalfxRealm
          ports:
            - containerPort: 8882
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
         - name: config
           configMap:
             name: {{ include "splunk-connect-for-snmp.name" . }}-sim
             items:
               - key: "sim-collector-config.yaml"
                 path: "sim-collector-config.yaml"
{{- end }}
