{{- if .Values.sim.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-connect-for-snmp.sim.fullname" . }}
  labels:
    {{- include "splunk-connect-for-snmp.sim.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
    {{- if .Values.sim.service.annotations }}
{{ toYaml .Values.sim.service.annotations | indent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
{{ toYaml .Values.commonAnnotations| indent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 8882
      name: metrics
    - port: 8883
      name: events
  selector:
    {{- include "splunk-connect-for-snmp.sim.selectorLabels" . | nindent 4 }}
{{- end }}
