apiVersion: v1
kind: ConfigMap
metadata:
  name: sc4snmp
data:
  config.yaml: |
    # Splunk Connect for SNMP Traps
    # Sample Configuration file
    snmp:
      communities:
        v1:
          - public
          - "my-area"
      mibs:
        url:
          - "https://mibs.thola.io/asn1/@mib@"
        load_list:  
          - "SNMPv2-MIB"
          - "SNMP-COMMUNITY-MIB"
          - "SNMPv2-CONF"
          # - "A10-COMMON-MIB"
          # - "A3COM-HUAWEI-BLG-MIB"
          # - "NET-SNMP-EXAMPLES-MIB"
---

