files:
  scheduler:
    inventory: |
      host,version,community,profile,freqinseconds
      #10.0.0.1,2c,public,basev1,300
    config:
      usernames:
        simulator:
          authKey: "auctoritas"
          privKey: "privatus"
        testUser:
          authKey: authpass
          privKey: privacypass
          contextName: "4c9184f37cff01bcdc32dc486ec36961"
          authProtocol: SHA
          privProtocol: AES
          securityEngineId: 8000000004030201
          securityName:
          authKeyType: 0
          privKeyType: 0
############################
#      ### Example of communities ###
#      communities:
#         public:
#           communityIndex:
#           contextEngineId:
#           contextName:
#           tag:
#           securityName:
#         my-area:
############################
#      ### Example of profile ###
#      profiles:
#        nameofprofile:
#          frequency: ###number_of_seconds###
#          varBinds:
#            - ['SNMPv2-MIB', 'sysDescr']
#            - ['SNMPv2-MIB', 'sysName', 0]
#            - 1.2.3.2.1.*
#            - 1.3.6.1.2.1.2.1.0
  traps:
    config: |
        communities:
          v2:
            - public
            - "my-area"
          v1:
#            - public
#            - "my-area"
          v3:
#            - userName: snmpv3test
#              authKey: AuthPass1
#              privKey: PrivPass2
#              securityEngineId: 8000000004030201
#            - userName: snmpv3test2
#              authProtocol: SHA
#              authKey: AuthPass11
#              privProtocol: aes
#              privKey: PrivPass22
#              securityEngineId: 8000000004030202
#            - userName: snmpv3test3
#              securityEngineId: 8000000004030203
#            - userName: testfdse
#              authKey: testfdse
#              privKey: testfdse
#              securityEngineId: 8000000903bc16f5802780