{{- $secretname := cat $.Release.Name "-rabbitmq-password" }}  
{{- $rabbitmqPasswordValue := (randAlpha 16) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretname) }}
{{- if $secret }}
{{- $rabbitmqPasswordValue = index $secret.data "rabbitmq-password" }}
{{- end -}}  

apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Release.Name }}-rabbitmq-password"
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  rabbitmq-password: {{ $rabbitmqPasswordValue }}
