splunk:
  enabled: true
  protocol: https
  host: ###LOAD_BALANCER_ID###
  token: ###SPLUNK_TOKEN###
  insecureSSL: "true"
  port: "8088"
image:
  repository: "snmp-local"
  tag: "latest"
  pullPolicy: "Never"
traps:
  replicaCount: 1
  communities:
    2c:
      - public
      - homelab
  #usernameSecrets:
  #  - sc4snmp-hlab-sha-aes
  #  - sc4snmp-hlab-sha-des

  #loadBalancerIP: The IP address in the metallb pool
  loadBalancerIP: ###LOAD_BALANCER_ID###
worker:
  poller:
    replicaCount: 4
    concurrency: 4
    prefetch: 1
  trap:
    replicaCount: 1
    concurrency: 8
    prefetch: 60
  sender:
    replicaCount: 1
    concurrency: 4
    prefetch: 60
  profilesReloadDelay: 1
  # replicas: Number of replicas for worker container should two or more
  # udpConnectionTimeout: timeout in seconds for SNMP operations
  #udpConnectionTimeout: 5
  logLevel: "DEBUG"
scheduler:
  logLevel: "INFO"
  customTranslations:
    IP-MIB:
      icmpOutEchoReps: myCustomName1
#  profiles: |
#    generic_switch:
#      frequency: 60
#      varBinds:
#        - ['SNMPv2-MIB', 'sysDescr']
#        - ['SNMPv2-MIB', 'sysName', 0]
#        - ['IF-MIB']
#        - ['TCP-MIB']
poller:
 # usernameSecrets:
 #   - sc4snmp-hlab-sha-aes
 #   - sc4snmp-hlab-sha-des
  inventory: |
    address,port,version,community,secret,securityEngine,walk_interval,profiles,SmartProfiles,delete
    ###LOAD_BALANCER_ID###,,2c,public,,,600,,,
sim:
  # sim must be enabled if you want to use signalFx
  enabled: false
#  signalfxToken: BCwaJ_Ands4Xh7Nrg
#  signalfxRealm: us0
mongodb:
  pdb:
    create: true
  persistence:
    storageClass: "microk8s-hostpath"
  volumePermissions:
    enabled: true
redis:
  architecture: standalone
  auth:
    enabled: false