apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongodb.service.port | default 27017 }}
      targetPort: 27017
  selector:
    app: {{ .Release.Name }}-mongodb
