apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "splunk-connect-for-snmp.traps.fullname" . }}
  labels:
    {{- include "splunk-connect-for-snmp.traps.labels" . | nindent 4 }}
spec:
  {{- if not .Values.traps.autoscaling.enabled }}
  replicas: {{ .Values.traps.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "splunk-connect-for-snmp.traps.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.traps.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "splunk-connect-for-snmp.traps.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.traps.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "splunk-connect-for-snmp.traps.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.traps.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.traps.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            [
              "celery", "trap",
            ]   
          env:
            - name: CONFIG_PATH
              value: /app/config/config.yaml
            - name: CELERY_BROKER_URL
              value: {{ include "splunk-connect-for-snmp.celery_url" . }}
            - name: MONGO_URI
              value: {{ include "splunk-connect-for-snmp.mongo_uri" . }}
            - name: LOG_LEVEL
              value: {{ .Values.traps.logLevel | default "INFO" }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /app/.venv/bin/celery
                - "inspect ping -d celery@$HOSTNAME"
          startupProbe:
            exec:
              command:
                - /app/.venv/bin/celery
                - "inspect ping -d celery@$HOSTNAME"
            failureThreshold: 180
            periodSeconds: 30
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
            - name: pysnmp-cache-volume
              mountPath: "/.pysnmp/"
              readOnly: false                
            - name: tmp
              mountPath: "/tmp/"
              readOnly: false                    

          resources:
            {{- toYaml .Values.traps.resources | nindent 12 }}
      {{- with .Values.traps.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.traps.podAntiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                    {{- include "splunk-connect-for-snmp.traps.selectorLabels" . | nindent 22 }}
      {{- else if eq .Values.traps.podAntiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "splunk-connect-for-snmp.traps.selectorLabels" . | nindent 22 }}
      {{- end }}
      {{- with .Values.traps.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: {{ include "splunk-connect-for-snmp.scheduler.fullname" . }}-config
            # An array of keys from the ConfigMap to create as files
            items:
              - key: "config.yaml"
                path: "config.yaml"
        - name: pysnmp-cache-volume
          emptyDir: {}    
        - name: tmp
          emptyDir: {}              