apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "splunk-connect-for-snmp.worker.fullname" . }}-sender
  labels:
    {{- include "splunk-connect-for-snmp.worker.sender.labels" . | nindent 4 }}
spec:
  {{- if not .Values.worker.sender.autoscaling.enabled }}
  replicas: {{ .Values.worker.sender.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "splunk-connect-for-snmp.worker.sender.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "splunk-connect-for-snmp.worker.sender.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "splunk-connect-for-snmp.serviceAccountName" . }}
      securityContext:
        fsGroup: 10001
      containers:
        - name: {{ .Chart.Name }}-worker-sender
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            [
              "celery", "worker-sender",
            ]
          env:
            - name: USER
              value: {{ .Values.deploymentUser | default "sc4snmp" | quote }}
            {{- include "environmental-variables" . | nindent 12 }}
            {{- include "environmental-variables-sender" . | nindent 12 }}
            {{- if .Values.splunk.mtls.enabled }}
            - name: SPLUNK_HEC_MTLS_CLIENT_CERT
              value: /app/hec-mtls/tls.crt
            - name: SPLUNK_HEC_MTLS_CLIENT_KEY
              value: /app/hec-mtls/tls.key
            - name: SPLUNK_HEC_MTLS_CA_CERT
              value: /app/hec-mtls/cacert.pem
            {{- end }}
            {{- if .Values.redis.auth.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.redis.auth.existingSecret }}
                  name: {{ .Values.redis.auth.existingSecret }}
                  key: {{ .Values.redis.auth.existingSecretPasswordKey | default "password" }}
                  {{- else }}
                  name: {{ .Release.Name }}-redis-secret
                  key: password
                  {{- end }}
            {{- end }}
          {{- if .Values.worker.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                {{- toYaml .Values.worker.livenessProbe.exec.command | nindent 16 }}
            initialDelaySeconds: {{ .Values.worker.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.worker.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.worker.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                {{- toYaml .Values.worker.readinessProbe.exec.command | nindent 16 }}
            initialDelaySeconds: {{ .Values.worker.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.worker.readinessProbe.periodSeconds }}
          {{- end }}
          volumeMounts:
            {{- if .Values.splunk.mtls.enabled }}
            - name: hec-mtls
              mountPath: "/app/hec-mtls"
              readOnly: true
            {{- end }}
            - name: config
              mountPath: "/app/config"
              readOnly: true
            - name: pysnmp-cache-volume
              mountPath: "/.pysnmp/"
              readOnly: false
            - name: tmp
              mountPath: "/tmp/"
              readOnly: false
          resources:
            {{- toYaml .Values.worker.sender.resources | nindent 12 }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.worker.podAntiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                    {{- include "splunk-connect-for-snmp.worker.sender.selectorLabels" . | nindent 22 }}
      {{- else if eq .Values.worker.podAntiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "splunk-connect-for-snmp.worker.sender.selectorLabels" . | nindent 22 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.splunk.mtls.enabled }}
        - name: hec-mtls
          secret:
            secretName: {{ .Values.splunk.mtls.secretRef }}
        {{- end }}
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: {{ include "splunk-connect-for-snmp.name" . }}-config
            # An array of keys from the ConfigMap to create as files
            items:
              - key: "config.yaml"
                path: "config.yaml"
        - name: pysnmp-cache-volume
          emptyDir: {}
        - name: tmp
          emptyDir: {}

