{{- if .Values.otel.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "splunk-connect-for-snmp.otel.fullname" . }}
  labels:
    {{- include "splunk-connect-for-snmp.otel.labels" . | nindent 4 }}
spec:
  {{- if not .Values.otel.autoscaling.enabled }}
  replicas: {{ .Values.otel.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "splunk-connect-for-snmp.otel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.otel.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "splunk-connect-for-snmp.otel.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "splunk-connect-for-snmp.otel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.otel.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-otel
          securityContext:
            {{- toYaml .Values.otel.securityContext | nindent 12 }}
          image: {{ .Values.otel.image | default "quay.io/signalfx/splunk-otel-collector" }}:{{ .Values.otel.tag | default "0.41.0" }}
          imagePullPolicy: {{ .Values.otel.pullPolicy | default "IfNotPresent" }}
          args: ["--config=/config/otel-collector-config.yaml"]
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: signalfxToken
              valueFrom:
                secretKeyRef:
                  name: {{ include "splunk-connect-for-snmp.name" . }}-otel
                  key: signalfxToken
            - name: signalfxRealm
              valueFrom:
                secretKeyRef:
                  name: {{ include "splunk-connect-for-snmp.name" . }}-otel
                  key: signalfxRealm
          ports:
            - containerPort: 8882
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
         - name: config
           configMap:
             name: {{ include "splunk-connect-for-snmp.name" . }}-otel
             items:
               - key: "otel-collector-config.yaml"
                 path: "otel-collector-config.yaml"
{{- end }}