name: Release-Notes-Preview

on:
  pull_request:
  issue_comment:
    types: [ edited ]

jobs:
  call-workflow-preview:
    permissions:
      contents: write
      packages: write
    uses: splunk/addonfactory-github-workflows/.github/workflows/reusable-release-notes.yaml@v1.4.1
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
